version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
    volumes: 
      - "D:/Projetos/Jenkins/data"
    networks: 
      - net
networks: 
  net: